// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glithoimbfoovrqxyrmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsaXRob2ltYmZvb3ZycXh5cm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5ODc1MDUsImV4cCI6MjA1NDU2MzUwNX0.l1ZmyAAuPzCRmtbZZdkeuTW01v6MyjudWqFEKdZp03Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);